### ISSUE TITLE
Link is not correct

### ISSUE THREAD

**Issue by kamtasingh27** [MRKaZ/StreamTapeExtractor#2]
That link loads up a short video which says you are trying to access streamtape from some other source.
Can you fix this?

**Comment by MRKaZ** [comment]
@kamtasingh27 can you show error log?

**Comment by kamtasingh27** [comment]
there is no error

**Comment by MRKaZ** [comment]
give me a one sec ill check!

**Comment by MRKaZ** [comment]
@kamtasingh27 which link type did you try?

**Comment by kamtasingh27** [comment]
i didn't exactly use your code
i was trying to make somthing similar in Flutter so copied the method.
The link loads up fine but it says that you are trying to access from a external source.

**Comment by kamtasingh27** [comment]
i guess i am doing something wrong because yours is working fine.

**Comment by MRKaZ** [comment]
@kamtasingh27 ohhhhh! im not flutter expert but i can help you!

**Comment by MRKaZ** [comment]
@kamtasingh27 
which part do you getting error like that? on getting response or splitting regex patterns?
1. first of all you need to get string response using volley or something HTTP library 
2. after get response match the regex patterns to export the download link!
(Go to your streamtape using browser recommended google chrome, after go to view source page (Ctrl+U) and search this pattern start with "<script>document.getElementById('vid'+'eolink')" end up with ";</script>" to get download link!)
did you got it? 😉

**Comment by kamtasingh27** [comment]
got it working now



&lt;div id="videolink" style="display:none;"&gt;//streamtape.com/get_video?id=xxxxxxxxxxxxxxx&amp;expires=1622112760&amp;ip=F0SOKRSUEI9XKxR&amp;token=4M_axNnM9KzZ&lt;/div&gt;
--
&nbsp; | &lt;script&gt;document.getElementById('vid'+'eolink').innerHTML = "//streamtape.com/get_v" + 'ideo?id=xxxxxxxxxxxxxxx&amp;expires=1622112760&amp;ip=F0SOKRSUEI9XKxR&amp;token=4M_axNnM9K8F';&lt;/script&gt;


 
i was fetching the above line
the lower one works
