### ISSUE TITLE
Not working in Android Studio

### ISSUE THREAD

**Issue by pcteckserv** [MRKaZ/StreamTapeExtractor#3]
You verification please??? Now not working for get the download link.

Thanks and good job

**Comment by MRKaZ** [comment]
@rebolinho let me check? give some time!
Thanks for the BUG report!

**Comment by MRKaZ** [comment]
> You verification please??? Now not working for get the download link.
> 
> Thanks and good job

You mean only link?. To me its able to extract filename and the poster thumb, Something wrong in the url extraction. im working on it!

**Comment by pcteckserv** [comment]
Thanks
