### ISSUE TITLE
Not working in Android 7,8,9

### ISSUE THREAD

**Issue by pcteckserv** [MRKaZ/StreamTapeExtractor#4]
I've been testing it and it only works from Android 10 onwards, all equipment with lower android even from 7 onwards does not return the url, nor does it give any information.
Could you check it out? Or is there a problem?

**Comment by pcteckserv** [comment]
And you can't for dood.ws either
For example this url: https://dood.ws/d/dzkbsmn86fwo

**Comment by MRKaZ** [comment]
@rebolinho It works also Android 9, What do you mean dood.ws?

**Comment by MRKaZ** [comment]
@rebolinho its not for dood.ws its only for streamtape.com have read the readme.md?

**Comment by pcteckserv** [comment]
Yes it only works from android 9 onwards... the ones before android 6 do not work at least.  some reason?

**Comment by MRKaZ** [comment]
@rebolinho Wait im not tested it on 7 and 8 give me  some time to check and fix it! and What do you mean dood.ws?

**Comment by pcteckserv** [comment]
for dood.ws or doostream is there a way to get the movie URL via API?  if yes you can develop.  we can talk in private.

**Comment by MRKaZ** [comment]
> 

Yeah man sure lets make some extractor for dood.ws lets talk, Telegram?

**Comment by MRKaZ** [comment]
@rebolinho I just tested dood.ws after your mention its simple to make

**Comment by rebolinho** [comment]
My telegram: @zequinhoptl
