### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by amanmamta** [MRKaZ/StreamTapeExtractor#5]
I have tried running it but the their are no results. Can you please check it once?

**Comment by MRKaZ** [comment]
@amanmamta Sure! man give me some time!

**Comment by amanmamta** [comment]
Can we talk. I would like to hire you for a small work.

**Comment by amanmamta** [comment]
It's based on link resolver itself. Just let me know how can I contact you. Please consider this as this an urgent request.

**Comment by MRKaZ** [comment]
You can contact me through telegram @Anubis9494

**Comment by amanmamta** [comment]
I have mssged you. please check it and reply

**Comment by MRKaZ** [comment]
@amanmamta Got it!
